### ISSUE TITLE
Publish APK at Github/F-Droid?

### ISSUE THREAD

**Issue by IzzySoft** [CosimoSguanci/Material-File-Manager#3]
Any plans to publish the `.apk` here at Github or to F-Droid, so folks without Playstore can use it as well?

**Comment by CosimoSguanci** [comment]
Probably I will publish the apk to F-Droid.

**Comment by IzzySoft** [comment]
Even better – though that might take some time. Thanks!

**Comment by ghost** [comment]
- [ ] Remove play-services
- [ ] Pull zlib from mavenCentral
- [ ] Fix https://github.com/CosimoSguanci/Material-File-Manager/issues/6

**Comment by IzzySoft** [comment]
@CosimoSguanci seems you got distracted?

**Comment by IzzySoft** [comment]
No answer for over 2 years and no commits since either suggests we must consider this dead. Thanks for trying, though!
