### ISSUE TITLE
Missing resources

### ISSUE THREAD

**Issue by veyndan** [CosimoSguanci/Material-File-Manager#6]
Many of the resources cannot be found (and hence the app can't compile) as I don't believe you have pushed it to GitHub, examples being:

@array/themes
R.mipmap.wallpaper_1376
R.mipmap.wallpaper_5870
R.mipmap.wallpaper_6713
R.mipmap.wallpaper_5114
R.mipmap.wallpaper_1088
R.mipmap.ic_search_white_24dp

**Comment by CosimoSguanci** [comment]
I don't know how to push this files

**Comment by veyndan** [comment]
In the terminal type:

`git add .`
`git commit -m "Add missing resources"`

Basically the new files that you have created aren't tracked or staged yet, so you do this by using `git add`. Using `.` just means to stage all the files. You can use `git status` before typing each line above to see this happen, and also what files are going to be committed.
